In [59]:
import pandas as pd
import numpy as np


In [60]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/Currency.csv")
df['date']=pd.to_datetime(df['date'])
df.dtypes


<ipython-input-60-620b3f4d3ebb>:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date']=pd.to_datetime(df['date'])


date    datetime64[ns]
ARS            float64
AUD            float64
BHD            float64
BWP            float64
BRL            float64
BND            float64
BGN            float64
CAD            float64
CLP            float64
CNY            float64
COP            float64
HRK            float64
CZK            float64
DKK            float64
HKD            float64
HUF            float64
ISK            float64
INR            float64
IDR            float64
IRR            float64
ILS            float64
JPY            float64
KZT            float64
KRW            float64
KWD            float64
LYD            float64
MYR            float64
MUR            float64
MXN            float64
NPR            float64
NZD            float64
NOK            float64
OMR            float64
PKR            float64
PHP            float64
PLN            float64
QAR            float64
RON            float64
RUB            float64
SAR            float64
SGD            float64
ZAR            float64
LKR        

In [79]:
df = df[["AED", "USD", "GBP", "INR", "PHP"]]
df

AED       USD       GBP       INR       PHP
0     0.383300  0.383300  0.624238  0.888135  0.877232
1     0.372694  0.372693  0.614776  0.879686  0.867326
2     0.372276  0.372277  0.610020  0.879309  0.866949
3     0.377304  0.377302  0.615615  0.883648  0.871951
4     0.378982  0.378981  0.621781  0.885162  0.873465
...        ...       ...       ...       ...       ...
3766  0.484169  0.483600  0.119048  0.097325  0.106029
3767  0.504358  0.503831  0.128527  0.113044  0.123346
3768  0.553961  0.553374  0.142199  0.123493  0.151026
3769  0.546989  0.546409  0.139933  0.122972  0.149112
3770  0.548894  0.548468  0.128647  0.113894  0.150243

[3771 rows x 5 columns]

In [62]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns, index=df.index)


In [63]:
xtrain=df[:3000]
xtest=df[3000:]
xtrain[:11]
xtest

AED       USD       GBP       INR       PHP
3000  0.337613  0.337310  0.669171  0.086507  0.328042
3001  0.337715  0.337314  0.669171  0.086508  0.328043
3002  0.346285  0.345936  0.671008  0.084110  0.336446
3003  0.359222  0.358714  0.657335  0.106005  0.371207
3004  0.361690  0.361286  0.661430  0.124322  0.370904
...        ...       ...       ...       ...       ...
3766  0.484169  0.483600  0.119048  0.097325  0.106029
3767  0.504358  0.503831  0.128527  0.113044  0.123346
3768  0.553961  0.553374  0.142199  0.123493  0.151026
3769  0.546989  0.546409  0.139933  0.122972  0.149112
3770  0.548894  0.548468  0.128647  0.113894  0.150243

[771 rows x 5 columns]

In [64]:
from keras.preprocessing.sequence import TimeseriesGenerator
xtrain_generator = TimeseriesGenerator(xtrain.values, xtrain.values,length=60, batch_size=1)
xtrain_generator[0]

(array([[[0.38330024, 0.38330042, 0.62423801, 0.88813509, 0.87723234],
         [0.37269376, 0.37269263, 0.61477573, 0.87968599, 0.86732561],
         [0.37227569, 0.37227739, 0.61001977, 0.8793091 , 0.86694892],
         [0.37730387, 0.37730213, 0.61561526, 0.88364762, 0.87195145],
         [0.37898182, 0.37898054, 0.62178146, 0.88516175, 0.87346507],
         [0.37501021, 0.3750096 , 0.61783195, 0.88155657, 0.8702426 ],
         [0.37433561, 0.37433614, 0.61856395, 0.88083555, 0.86947635],
         [0.3948198 , 0.39481893, 0.61444901, 0.89907546, 0.88272626],
         [0.39403974, 0.3940408 , 0.6156897 , 0.8984234 , 0.88167276],
         [0.4257271 , 0.42572806, 0.6217401 , 0.92360591, 0.90340372],
         [0.4253879 , 0.4253861 , 0.62177319, 0.9233545 , 0.90459014],
         [0.38745047, 0.38744932, 0.61899819, 0.8964438 , 0.8841373 ],
         [0.38688894, 0.38688752, 0.61845642, 0.89584065, 0.88349342],
         [0.39422596, 0.39422574, 0.62285258, 0.89833801, 0.88946918],
      

In [65]:
from keras.models import Sequential
from keras.layers import Dense,LSTM,Dropout
from keras.optimizers import Adam

In [66]:
model = Sequential()
model.add(LSTM(128, activation='relu', return_sequences=True, input_shape=(60, 5)))
model.add(Dropout(0.2))
model.add(LSTM(128, activation='relu', return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(128, activation='relu'))
model.add(Dense(5))


In [67]:
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='mse')

In [68]:
model.fit(xtrain_generator,epochs=3)

Epoch 1/3
40/40 [==============================] - 5s 51ms/step - loss: 0.1147
Epoch 2/3
40/40 [==============================] - 2s 54ms/step - loss: 0.0027
Epoch 3/3
40/40 [==============================] - 2s 51ms/step - loss: 0.0012


In [69]:
test_sample=xtrain.tail(60)
test_sample=test_sample.values
test_sample=test_sample.reshape(1,60,5)
model.predict(test_sample)
test_sample

1/1 [==============================] - 0s 379ms/step


array([[[0.43788612, 0.43788514, 0.64870018, 0.92385746, 0.88677171],
        [0.43149638, 0.43149605, 0.64576803, 0.91478154, 0.89015231],
        [0.43117238, 0.43117153, 0.64594586, 0.91450997, 0.88992935],
        [0.42675041, 0.42675046, 0.65398549, 0.90833926, 0.88680469],
        [0.42626868, 0.42626892, 0.65292677, 0.90790707, 0.88637389],
        [0.42684827, 0.42684816, 0.65264142, 0.90847232, 0.88691284],
        [0.42747537, 0.42747625, 0.65178535, 0.90903462, 0.88747334],
        [0.42776896, 0.42776936, 0.65114846, 0.90920505, 0.88815439],
        [0.42831625, 0.4283172 , 0.65112365, 0.90983308, 0.88871333],
        [0.41974878, 0.41975072, 0.65035442, 0.91110341, 0.88284053],
        [0.42096592, 0.42096503, 0.65028825, 0.91206494, 0.88353696],
        [0.42341159, 0.4234111 , 0.64896899, 0.91357202, 0.87529163],
        [0.42312465, 0.42312497, 0.64836933, 0.91309122, 0.87607755],
        [0.42890629, 0.42890691, 0.66231876, 0.91967276, 0.88816484],
        [0.42915333,

In [70]:
np.append(test_sample[:,1:],[[[.2,1,2,3,3]]],axis=1)
test_sample

array([[[0.43788612, 0.43788514, 0.64870018, 0.92385746, 0.88677171],
        [0.43149638, 0.43149605, 0.64576803, 0.91478154, 0.89015231],
        [0.43117238, 0.43117153, 0.64594586, 0.91450997, 0.88992935],
        [0.42675041, 0.42675046, 0.65398549, 0.90833926, 0.88680469],
        [0.42626868, 0.42626892, 0.65292677, 0.90790707, 0.88637389],
        [0.42684827, 0.42684816, 0.65264142, 0.90847232, 0.88691284],
        [0.42747537, 0.42747625, 0.65178535, 0.90903462, 0.88747334],
        [0.42776896, 0.42776936, 0.65114846, 0.90920505, 0.88815439],
        [0.42831625, 0.4283172 , 0.65112365, 0.90983308, 0.88871333],
        [0.41974878, 0.41975072, 0.65035442, 0.91110341, 0.88284053],
        [0.42096592, 0.42096503, 0.65028825, 0.91206494, 0.88353696],
        [0.42341159, 0.4234111 , 0.64896899, 0.91357202, 0.87529163],
        [0.42312465, 0.42312497, 0.64836933, 0.91309122, 0.87607755],
        [0.42890629, 0.42890691, 0.66231876, 0.91967276, 0.88816484],
        [0.42915333,

In [71]:
prediction=[]
for i in range(100):
  pred=model.predict(test_sample)
  prediction.append(np.array(pred))
  test_sample=np.append(test_sample[:,1:],[pred],axis=1)


1/1 [==============================] - 0s 39ms/step


In [72]:
prediction

[array([[0.39232424, 0.391576  , 0.66432995, 0.8874191 , 0.8055467 ]],
       dtype=float32),
 array([[0.391826  , 0.3910307 , 0.6634201 , 0.88619906, 0.8043798 ]],
       dtype=float32),
 array([[0.39137262, 0.39054394, 0.6625959 , 0.88510907, 0.8033357 ]],
       dtype=float32),
 array([[0.39096698, 0.39011505, 0.6618564 , 0.88414764, 0.80241257]],
       dtype=float32),
 array([[0.39060745, 0.3897392 , 0.66119504, 0.883304  , 0.80159974]],
       dtype=float32),
 array([[0.39029014, 0.3894094 , 0.6606024 , 0.8825617 , 0.8008821 ]],
       dtype=float32),
 array([[0.3900093 , 0.38911775, 0.66006833, 0.8819032 , 0.80024374]],
       dtype=float32),
 array([[0.38975874, 0.3888566 , 0.6595829 , 0.8813116 , 0.7996688 ]],
       dtype=float32),
 array([[0.38953248, 0.3886188 , 0.6591368 , 0.88077134, 0.7991432 ]],
       dtype=float32),
 array([[0.38932505, 0.38839853, 0.658722  , 0.8802698 , 0.79865515]],
       dtype=float32),
 array([[0.38913158, 0.38819095, 0.6583317 , 0.8797964 , 0.7

In [73]:
combined_array=np.vstack(prediction)
dfpred=pd.DataFrame(combined_array, columns=["AED", "USD", "GBP", "INR", "PHP"])
dfpred=pd.DataFrame(scaler.inverse_transform(dfpred), columns=dfpred.columns)
tail=pd.DataFrame(scaler.inverse_transform(xtest.tail(100)),columns=["AED", "USD", "GBP", "INR", "PHP"])
print(dfpred)
print(tail)

         AED       USD       GBP        INR        PHP
0   3.947291  1.074610  0.854734  89.543312  61.593300
1   3.946767  1.074453  0.854514  89.510933  61.571541
2   3.946290  1.074314  0.854315  89.482002  61.552067
3   3.945863  1.074191  0.854136  89.456490  61.534851
4   3.945485  1.074083  0.853976  89.434097  61.519691
..       ...       ...       ...        ...        ...
95  3.931130  1.069779  0.847715  88.546227  60.921925
96  3.931012  1.069743  0.847665  88.538933  60.917038
97  3.930894  1.069708  0.847614  88.531677  60.912186
98  3.930777  1.069673  0.847564  88.524467  60.907356
99  3.930661  1.069638  0.847514  88.517303  60.902554

[100 rows x 5 columns]
         AED       USD       GBP        INR        PHP
0   4.125222  1.123045  0.735103  71.919370  50.738606
1   4.082480  1.111500  0.727922  71.258274  50.116720
2   4.082480  1.111500  0.727922  71.258274  50.116720
3   4.079431  1.110669  0.727645  71.190580  50.198897
4   4.139094  1.126852  0.733387  72.1320

In [74]:
from sklearn.metrics import mean_squared_error,r2_score
lst=[]
for i in range(0,100):

  lst.append(r2_score(tail.values[i], dfpred.values[i]))
print(f"The average R2 of the Model is : {np.mean(lst)*100} %")

The average R2 of the Model is : 86.3210711975048 %


In [75]:
!pip install anvil-uplink


  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)


In [76]:
import anvil.server

anvil.server.connect("server_HOUYLQN6Z6OZQCZWWN5HUUPH-7QKTEMFQCKZZP776")

**FUNCTION**

In [90]:


@anvil.server.callable

def pred(iterations):
    predictions = []
    for i in range(iterations):

        test_sample=xtrain.tail(60)
        test_sample=test_sample.values
        test_sample=test_sample.reshape(1,60,5)
        pred = model.predict(test_sample)
        predictions.append(np.array(pred))
        test_sample = np.append(test_sample[:, 1:], [pred], axis=1)
    predictions = np.array(predictions).reshape(-1, predictions[0].shape[1])
    predictions=scaler.inverse_transform(predictions)
    formatted_predictions = (
        f"United Arab Emirates(AED): {predictions[-1, 0]:.2f} د.إ\n"
        f"USA(USD): {predictions[-1, 1]:.2f} $\n"
        f"UK(GBP): {predictions[-1, 2]:.2f} £\n"
        f"INDIA(INR): {predictions[-1, 3]:.2f} ₹\n"
        f"Philippines(PHP): {predictions[-1, 4]:.2f} ₱"
    )
    return formatted_predictions



TypeError: list indices must be integers or slices, not tuple